name = "Local Verity"
author = "MelonLord"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8817c669c271ac9cca81287997168d6dc034431e0b22c7ebd6dafa855e3a68d"

[versions]
forge = "47.4.26"
minecraft = "1.20.1"
