name = "Local Verity"
author = "MelonLord"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba6b3a9f1f2c59fd218670fb32ffa8684e9e5f5578c225d60a8a8b575a0e642d"

[versions]
forge = "47.4.26"
minecraft = "1.20.1"
