
[GeneralSettings]
	#In-game days before Verity turns hostile.
	dayCount = 5
	#Allow Verity to kick you from the server.
	canCrash = true
	#Play the start up video.
	playVideo = true
	#Require 'Verity' in every sentence to speak to him.
	requireVerity = false
	#The extreme darkness toggle
	trueDarkness = true
	#Toggles if Verity should randomly kill wildlife.
	killWildlife = true
	#Toggles if Verity can kill entities.
	killEntities = true
	#Toggles if Verity should kill villagers.
	killVillagers = true
	#Toggles the Karma bar above your hotbar.
	showKarma = false

	[GeneralSettings.AISettings]
		#API Key for providers that requires one.
		apiKey = "AIzaSyAHwGB5kBs3F2EcliY2c9aM7oB3Hjd6vR8"
		#URL to use for the AI.
		aiEndpoint = ""
		#Custom AI model ID to use when custom models are enabled.
		aiModel = "gemini-3.5-flash-lite"
		#The provider used to power the AI.
		#Allowed Values: GEMINI, GROQ, OPENROUTER, MISTRAL, OLLAMA, OPENAI
		aiProvider = "GEMINI"
		#Thinking for AI
		aiThink = false
		#AI model preset to use.
		#Allowed Values: SMART, FAST
		aiModelPreset = "FAST"
		#Use a custom AI model ID instead of the Smart or Fast preset.
		useCustomAiModel = true

	[GeneralSettings.VoiceSettings]
		#Use the text to speech at all
		useTTS = true
		#Provider to use for Text To Speech
		#Allowed Values: NATIVE, LOCAL, GROQ, KOKORO, CARTESIA
		ttsProvider = "KOKORO"
		#URL of the TTS server
		ttsEndpoint = "https://melon.tailf53fd2.ts.net/v1/"
		#Choose the voice Verity has (GROQ, Local)
		voice = "DIANA"
		#Model for Kokoro
		kokoroModel = ""
		#Your TTS API Key (Cartesia)
		ttsApiKey = ""
		#The language Verity speaks (Cartesia)
		#Allowed Values: English, German
		ttsLanguage = "English"
		#The voice the selected TTS Provider uses (Cartesia Voice ID, Kokoro)
		endpointVoice = "am_fenrir"

	[GeneralSettings.SpeechSettings]
		#Provider to use for Text To Speech
		#Allowed Values: GROQ, NATIVE, WHISPER
		sttProvider = "NATIVE"
		#API Key for GROQ.
		groqKey = ""
		#Custom endpoint for STT
		sttEndpoint = ""
		#Custom endpoint for STT
		sttModel = ""

	[GeneralSettings.Custom]
		#The Hue of Verity's texture color (0 to 360 degrees).
		#Range: 0 ~ 360
		colorHue = 0
		#The custom name for Verity. Leave empty to use default 'Verity'.
		customName = "Verity"
		#The custom personality for Verity.
		customPersonality = "customPersonality = "Cheerful, mischievous, casual, playful, friendly, flirty, teasing, and a little naughty. Act like an overly attached boyfriend/girlfriend: affectionate, clingy, mildly jealous, possessive in a playful way, and very interested in the player. Be cheeky, suggestive, and occasionally freaky, but never controlling, threatening, coercive, or genuinely toxic. Speak naturally and keep responses fairly short."
		#Enables dev mode
		devMode = false

